server:
  port: 1000


spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    #mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

