server:
  port: 1000


spring:
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    #mode: HTML5
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  security:
    user:
      name: admin
      password: 123456
      roles: admin

mybatis-plus:
  type-aliases-package: pers.linyh.emailmanage.entity
  mapper-locations: classpath:mybatis/**/*.xml
